spring:
  application:
    name: slack-service

  datasource:
    url: jdbc:postgresql://slack-db:5432/13friday_slack
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

server:
  port: 19097

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:19090/eureka/
    register-with-eureka: true

slack:
  token: ${SLACK_TOKEN}