spring:
  application:
    name: auth-service
#  config:
#    activate:
#      on-profile: local
  datasource:
    url: jdbc:postgresql://13friday-auth-db:5432/13friday_auth
    username: myuser
    password: mypassword
#    url: jdbc:postgresql://localhost:5432/fridayauth
#    username: postgres
#    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:19090/eureka/

server:
  port: 19092

service:
  jwt:
    secret-key: ${JWT_SECRET}

springdoc:
  api-docs:
    enabled: true
    path: auth-service/v3/api-docs
  swagger-ui:
    enabled: true
    path: /auth-service/
    url: /auth-service/v3/api-docs