spring:
  application:
    name: hub-service

  datasource:
    url: jdbc:postgresql://hub-db:5432/13friday_hub  # docker 환경
    username: ${HUB_DB_USERNAME}
    password: ${HUB_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update #none 으로 설정시 테이블이 없으면 초기데이터 생성과정에서 에러 발생 우려
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  data:
    redis:
      host: hub-redis
      port: 6379
      timeout: 6000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
          max-wait: 1000ms

server:
  port: 19093

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:19090/eureka/
    register-with-eureka: true

springdoc:
  api-docs:
    enabled: true
    path: /hub-service/v3/api-docs
  swagger-ui:
    enabled: true
    path: /hub-service/
    url: /hub-service/v3/api-docs

open-route-api-key: ${OPEN-ROUTE-API-KEY}