spring:
  application:
    name: hub-service

  datasource:
    url: jdbc:postgresql://hub-db:5432/13friday_hub  # docker 환경
    username: ${HUB_DB_USERNAME}
    password: ${HUB_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  data:
    redis:
      host: 13friday_hub-route
      port: 6379
      password: "1234"
      timeout: 6000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
          max-wait: 1000ms

server:
  port: 19093

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:19090/eureka/
    register-with-eureka: true


open-route-api-key: ${OPEN-ROUTE-API-KEY}