spring:
  application:
    name: hub-service

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true



  datasource:
    url: jdbc:postgresql://hub-db:5432/13friday_hub
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver


server:
  port: 19093

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:19090/eureka/
    register-with-eureka: true
