services:
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: 13friday-eureka-server
    ports:
      - "19090:19090"

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: 13friday-gateway
    ports:
      - "19091:19091"
    depends_on:
      - eureka-server

  hub-service:
    build:
      context: ./hub-service
      dockerfile: Dockerfile
    container_name: 13friday-hub-service
    ports:
      - "19093:19093"
    depends_on:
      - hub-db
      - eureka-server

  hub-db:
    image: postgres
    container_name: 13friday-hub-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=13friday_hub

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: 13friday-order-service
    ports:
      - "19094:19094"
    depends_on:
      - order-db
      - eureka-server

  order-db:
    image: postgres
    container_name: 13friday-order-db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=${ORDER_DB_USER}
      - POSTGRES_PASSWORD=${ORDER_DB_PASSWORD}
      - POSTGRES_DB=13friday_order

  company-service:
    build:
      context: ./company-service
      dockerfile: Dockerfile
    container_name: 13friday-company-service
    volumes:
      - ./company-service:/app/company-service
    ports:
      - "19096:19096"
    depends_on:
      - company-db
      - eureka-server

  company-db:
    image: postgres
    container_name: 13friday-company-db
    volumes:
      - ./db_data/company:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=13friday_company

  slack-service:
    build:
      context: ./slack-service
      dockerfile: Dockerfile
    container_name: 13friday-slack-service
    volumes:
      - ./slack-service:/app/slack-service
    ports:
      - "19097:19097"
    depends_on:
      - slack-db
      - eureka-server

  slack-db:
    image: postgres
    container_name: 13friday-slack-db
    volumes:
      - ./db_data/slack:/var/lib/postgresql/data
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=13friday_slack

volumes:
  db_data: