services:
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: 13friday-eureka-server
    ports:
      - "19090:19090"

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: 13friday-gateway
    ports:
      - "19091:19091"
    depends_on:
      - eureka-server

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mem

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: 13friday-auth-service
    volumes:
      - ./auth-service:/app/auth-service
    ports:
      - "19092:19092"
    env_file:
      - .env
    depends_on:
      - auth-db
      - eureka-server

  auth-db:
    image: postgres
    container_name: 13friday-auth-db
    volumes:
      - ./db_data/auth:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=13friday_auth

  hub-service:
    build:
      context: ./hub-service
      dockerfile: Dockerfile
    container_name: 13friday-hub-service
    ports:
      - "19093:19093"
    depends_on:
      - hub-db
      - redis
      - eureka-server
    environment:
      - OPEN_ROUTE_API_KEY=${OPEN-ROUTE-API-KEY}
    env_file:
      - .env

  hub-db:
    image: postgres
    container_name: 13friday-hub-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${HUB_DB_USERNAME}
      - POSTGRES_PASSWORD=${HUB_DB_PASSWORD}
      - POSTGRES_DB=13friday_hub
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: hub-redis
    ports:
      - "6379:6379"
    restart: always

  delivery-redis:
    image: redis:latest
    container_name: delivery-redis
    ports:
      - "6380:6379"   # 외부에 열리는 포트는 다르게, 내부 Redis는 기본 포트 사용
    restart: always


  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: 13friday-order-service
    ports:
      - "19094:19094"
    depends_on:
      - order-db
      - eureka-server
    env_file:
      - .env

  order-db:
    image: postgres
    container_name: 13friday-order-db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=${ORDER_DB_USER}
      - POSTGRES_PASSWORD=${ORDER_DB_PASSWORD}
      - POSTGRES_DB=13friday_order
    env_file:
      - .env

  delivery-service:
    build:
      context: ./delivery-service
      dockerfile: Dockerfile
    container_name: 13friday-delivery-service
    ports:
      - "19095:19095"
    depends_on:
      - delivery-db
      - delivery-redis
      - eureka-server
    env_file:
      - .env

  delivery-db:
    image: postgres
    container_name: 13friday-delivery-db
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=${DELIVERY_DB_USER}
      - POSTGRES_PASSWORD=${DELIVERY_DB_PASSWORD}
      - POSTGRES_DB=13friday_delivery
    env_file:
      - .env

  company-service:
    build:
      context: ./company-service
      dockerfile: Dockerfile
    container_name: 13friday-company-service
    volumes:
      - ./company-service:/app/company-service
    env_file:
      - .env
    ports:
      - "19096:19096"
    depends_on:
      - company-db
      - eureka-server

  company-db:
    image: postgres
    container_name: 13friday-company-db
    volumes:
      - ./db_data/company:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=13friday_company

  slack-service:
    build:
      context: ./slack-service
      dockerfile: Dockerfile
    container_name: 13friday-slack-service
    volumes:
      - ./slack-service:/app/slack-service
    ports:
      - "19097:19097"
    env_file:
      - .env
    depends_on:
      - slack-db
      - eureka-server

  slack-db:
    image: postgres
    container_name: 13friday-slack-db
    volumes:
      - ./db_data/slack:/var/lib/postgresql/data
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=13friday_slack

volumes:
  db_data: