spring:
  application:
    name: order-service


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true



  datasource:
    url: jdbc:postgresql://company-db:5432/friday_order
    username: ${ORDER_DB_USER}
    password:  ${ORDER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver


server:
  port: 19094

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://eureka-server:19090/eureka/
    register-with-eureka: true



