spring:
  application:
    name: delivery-service


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true



  datasource:
    url: jdbc:postgresql://delivery-db:5432/13friday_delivery
    username: ${DELIVERY_DB_USER}
    password: ${DELIVERY_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver


server:
  port: 19095

eureka:
  client:
    #    enabled: false
    service-url:
      defaultZone: http://eureka-server:19090/eureka/
    register-with-eureka: true
